version: "3"

services:
  app:
    build: .
    container_name: app
    expose:
      - 8000
    depends_on:
      - db
  db:
    image: postgres:14.2
    container_name: postgresdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1111
      - POSTGRES_DB=db
    restart: always
    volumes:
      - ./storages/postgresdata:/var/lib/postgresql/data
    expose:
      - 5432
